apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- workloads/namespace.yaml
- crds/orchestration.gputpu.io_heterogeneousclusters.yaml
- rbac/role.yaml
- workloads/operator.yaml
- workloads/deviceclasses.yaml
- workloads/dra-driver.yaml
- workloads/worker-rbac.yaml
